[package]
name = "my_cms"
version = "0.1.0"
authors = ["esposm03 <36164633+esposm03@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = { version = "3.3.2", default-features = false, features = [ "rustls" ] }

[dev-dependencies]
reqwest = "0.10.10"
tokio = { version = "1.0.1", features = ["rt-multi-thread"] }
